# Generated by Django 2.2.4 on 2019-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Indica o Nome do Patrocinador', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='patrocinadores')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o Patrocinador está ativo ou não')),
            ],
        ),
    ]
