# Generated by Django 2.2.4 on 2019-08-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='leitura',
            field=models.BooleanField(default=True, help_text='Informa se o participante leu o regulamento e Política de Privacidade.'),
        ),
    ]
