# Generated by Django 2.2.4 on 2019-08-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_cadastro_leitura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='leitura',
            field=models.BooleanField(default=False),
        ),
    ]
